//! Parallel agent execution engine — the "Kubernetes for AI agents."
//!
//! Supports:
//! - Task DAG execution (dependency-aware scheduling)
//! - Worker pool with configurable concurrency
//! - Process-level isolation per agent
//! - Deterministic audit trail across parallel execution
//! - Retry, cancellation, and partial completion
//!
//! Architecture:
//!   API/CLI → Orchestrator (DAG planner) → Task Queue → Worker Pool → Agents
//!   Each worker pulls tasks, executes them, and emits results + new tasks.

use std::collections::{BTreeMap, VecDeque};
use std::sync::{Arc, Mutex};
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Unique identifier for a parallel run.
pub type RunId = String;
pub type TaskId = String;

/// A task in the execution DAG.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentTask {
    pub id: TaskId,
    pub run_id: RunId,
    pub template: String,
    pub prompt: String,
    pub model: Option<String>,
    pub deps: Vec<TaskId>,
    pub priority: u8,
    pub status: TaskStatus,
    pub result: Option<TaskResult>,
    pub created_at: u64,
    pub started_at: Option<u64>,
    pub completed_at: Option<u64>,
    /// Isolated working directory for this task.
    pub work_dir: Option<PathBuf>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskStatus {
    Pending,
    Queued,
    Running,
    Completed,
    Failed,
    Cancelled,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskResult {
    pub success: bool,
    pub summary: String,
    pub iterations: usize,
    pub tool_invocations: u32,
    pub audit_hash: String,
    /// Input tokens consumed by this task (0 if unavailable).
    #[serde(default)]
    pub tokens_in: u32,
    /// Output tokens generated by this task (0 if unavailable).
    #[serde(default)]
    pub tokens_out: u32,
    /// Estimated cost in USD (0.0 if unavailable).
    #[serde(default)]
    pub cost_usd: f32,
}

/// Aggregated cost/token summary for a complete parallel run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RunCost {
    pub run_id: RunId,
    pub total_tokens_in: u64,
    pub total_tokens_out: u64,
    pub total_tokens: u64,
    pub estimated_cost_usd: f64,
    pub task_count: usize,
    pub tasks_with_cost: usize,
}

impl RunCost {
    #[must_use] pub fn from_run(run: &ParallelRun) -> Self {
        let mut total_in: u64 = 0;
        let mut total_out: u64 = 0;
        let mut total_cost: f64 = 0.0;
        let mut with_cost = 0usize;
        for task in &run.tasks {
            if let Some(res) = &task.result {
                total_in += u64::from(res.tokens_in);
                total_out += u64::from(res.tokens_out);
                total_cost += f64::from(res.cost_usd);
                if res.tokens_in > 0 || res.cost_usd > 0.0 { with_cost += 1; }
            }
        }
        RunCost {
            run_id: run.id.clone(),
            total_tokens_in: total_in,
            total_tokens_out: total_out,
            total_tokens: total_in + total_out,
            estimated_cost_usd: total_cost,
            task_count: run.tasks.len(),
            tasks_with_cost: with_cost,
        }
    }
}

/// A semantic conflict detected between parallel worker outputs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SemanticConflict {
    /// File where the conflict was detected.
    pub file: String,
    /// Line number (1-indexed).
    pub line: u32,
    /// Human-readable description of the conflict.
    pub message: String,
    /// Severity: "error" | "warning".
    pub severity: String,
    /// Which task(s) likely caused the conflict.
    pub suspected_tasks: Vec<TaskId>,
}

/// A parallel execution run — a DAG of tasks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParallelRun {
    pub id: RunId,
    pub tasks: Vec<AgentTask>,
    pub status: RunStatus,
    pub created_at: u64,
    pub max_concurrency: usize,
    /// Semantic conflicts detected during post-merge LSP validation.
    #[serde(default)]
    pub conflicts: Vec<SemanticConflict>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RunStatus {
    Running,
    Completed,
    PartiallyCompleted,
    Failed,
    Cancelled,
}

/// The task queue — dependency-aware, priority-scheduled.
pub struct TaskQueue {
    tasks: VecDeque<AgentTask>,
}

impl Default for TaskQueue {
    fn default() -> Self {
        Self::new()
    }
}

impl TaskQueue {
    #[must_use] pub fn new() -> Self {
        Self { tasks: VecDeque::new() }
    }

    /// Add a task to the queue.
    pub fn enqueue(&mut self, task: AgentTask) {
        // Insert by priority (higher priority = earlier in queue)
        let pos = self.tasks.iter().position(|t| t.priority < task.priority);
        match pos {
            Some(i) => self.tasks.insert(i, task),
            None => self.tasks.push_back(task),
        }
    }

    /// Get the next task whose dependencies are all completed.
    pub fn poll(&mut self, completed: &[TaskId]) -> Option<AgentTask> {
        let pos = self.tasks.iter().position(|t| {
            t.status == TaskStatus::Queued
                && t.deps.iter().all(|dep| completed.contains(dep))
        });
        pos.map(|i| self.tasks.remove(i).unwrap())
    }

    #[must_use] pub fn len(&self) -> usize {
        self.tasks.len()
    }

    #[must_use] pub fn is_empty(&self) -> bool {
        self.tasks.is_empty()
    }
}

/// The parallel execution orchestrator.
pub struct Orchestrator {
    runs: BTreeMap<RunId, ParallelRun>,
    queue: TaskQueue,
    completed_tasks: Vec<TaskId>,
    max_workers: usize,
    active_workers: usize,
}

impl Orchestrator {
    #[must_use] pub fn new(max_workers: usize) -> Self {
        Self {
            runs: BTreeMap::new(),
            queue: TaskQueue::new(),
            completed_tasks: Vec::new(),
            max_workers,
            active_workers: 0,
        }
    }

    /// Submit a parallel run with a DAG of tasks.
    pub fn submit(&mut self, run: ParallelRun) -> RunId {
        let run_id = run.id.clone();
        // Enqueue all tasks that have no dependencies
        for task in &run.tasks {
            let mut queued = task.clone();
            queued.status = TaskStatus::Queued;
            self.queue.enqueue(queued);
        }
        self.runs.insert(run_id.clone(), run);
        run_id
    }

    /// Get the next task ready for execution (deps satisfied, worker available).
    pub fn next_task(&mut self) -> Option<AgentTask> {
        if self.active_workers >= self.max_workers {
            return None;
        }
        if let Some(mut task) = self.queue.poll(&self.completed_tasks) {
            task.status = TaskStatus::Running;
            task.started_at = Some(now_epoch());
            self.active_workers += 1;
            Some(task)
        } else {
            None
        }
    }

    /// Report a task completion.
    pub fn complete_task(&mut self, task_id: &str, result: TaskResult) {
        self.completed_tasks.push(task_id.to_string());
        self.active_workers = self.active_workers.saturating_sub(1);

        // Update the run
        for run in self.runs.values_mut() {
            for task in &mut run.tasks {
                if task.id == task_id {
                    task.status = if result.success { TaskStatus::Completed } else { TaskStatus::Failed };
                    task.completed_at = Some(now_epoch());
                    task.result = Some(result.clone());
                }
            }
            // Check if run is complete
            let all_done = run.tasks.iter().all(|t| {
                matches!(t.status, TaskStatus::Completed | TaskStatus::Failed | TaskStatus::Cancelled)
            });
            if all_done {
                let all_success = run.tasks.iter().all(|t| t.status == TaskStatus::Completed);
                run.status = if all_success { RunStatus::Completed }
                    else if run.tasks.iter().any(|t| t.status == TaskStatus::Completed) { RunStatus::PartiallyCompleted }
                    else { RunStatus::Failed };
            }
        }
    }

    /// Cancel a task.
    pub fn cancel_task(&mut self, task_id: &str) {
        for run in self.runs.values_mut() {
            for task in &mut run.tasks {
                if task.id == task_id && task.status != TaskStatus::Completed {
                    task.status = TaskStatus::Cancelled;
                }
            }
        }
    }

    /// Get a run's status.
    #[must_use] pub fn get_run(&self, run_id: &str) -> Option<&ParallelRun> {
        self.runs.get(run_id)
    }

    /// List all runs.
    #[must_use] pub fn list_runs(&self) -> Vec<&ParallelRun> {
        self.runs.values().collect()
    }

    #[must_use] pub fn active_count(&self) -> usize {
        self.active_workers
    }

    #[must_use] pub fn pending_count(&self) -> usize {
        self.queue.len()
    }

    /// Persist a completed run for later polling without re-queuing its tasks.
    /// Used to write back results after `execute_parallel_run` finishes.
    pub fn register_completed_run(&mut self, run: ParallelRun) {
        self.runs.insert(run.id.clone(), run);
    }

    /// Append a completed run to the durable JSONL run log.
    pub fn persist_run(run: &ParallelRun, workspace_root: &std::path::Path) {
        let log_path = workspace_root.join(".tachy").join("runs.jsonl");
        if let Ok(line) = serde_json::to_string(run) {
            let mut file = std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open(&log_path)
                .unwrap_or_else(|e| panic!("cannot open runs log: {e}"));
            use std::io::Write;
            let _ = writeln!(file, "{line}");
        }
    }

    /// Load historical runs from the JSONL run log on daemon startup.
    #[must_use] pub fn load_run_history(workspace_root: &std::path::Path) -> Vec<ParallelRun> {
        let log_path = workspace_root.join(".tachy").join("runs.jsonl");
        let content = match std::fs::read_to_string(&log_path) {
            Ok(c) => c,
            Err(_) => return Vec::new(),
        };
        content.lines()
            .filter(|l| !l.trim().is_empty())
            .filter_map(|l| serde_json::from_str(l).ok())
            .collect()
    }
}

/// Execute a parallel run using a thread pool.
/// Each task runs in its own thread with an isolated working directory.
pub fn execute_parallel_run(
    run: ParallelRun,
    state: &Arc<Mutex<super::DaemonState>>,
) -> ParallelRun {
    let max_concurrency = run.max_concurrency.min(8); // cap at 8 parallel agents
    let orchestrator = Arc::new(Mutex::new(Orchestrator::new(max_concurrency)));

    // Submit the run
    {
        let mut orch = orchestrator.lock().unwrap();
        orch.submit(run.clone());
    }

    // Worker loop — spawn threads that pull and execute tasks
    let mut handles = Vec::new();

    loop {
        let task = {
            let mut orch = orchestrator.lock().unwrap();
            orch.next_task()
        };

        if let Some(task) = task {
            let orch = Arc::clone(&orchestrator);
            let bg_state = Arc::clone(state);
            let task_id = task.id.clone();

            let handle = std::thread::spawn(move || {
                // Execute the agent task
                let result = execute_single_task(&task, &bg_state);
                // Publish task_complete event to the live SSE bus
                bg_state.lock().unwrap_or_else(std::sync::PoisonError::into_inner)
                    .publish_event("task_complete", serde_json::json!({
                        "task_id": task_id,
                        "run_id": task.run_id,
                        "success": result.success,
                        "iterations": result.iterations,
                        "tokens_in": result.tokens_in,
                        "tokens_out": result.tokens_out,
                    }));
                let mut orch = orch.lock().unwrap();
                orch.complete_task(&task_id, result);
            });
            handles.push(handle);
        } else {
            // Check if all tasks are done
            let orch = orchestrator.lock().unwrap();
            if orch.pending_count() == 0 && orch.active_count() == 0 {
                break;
            }
            drop(orch);
            // Wait a bit before polling again
            std::thread::sleep(std::time::Duration::from_millis(100));
        }
    }

    // Wait for all workers
    for handle in handles {
        let _ = handle.join();
    }

    // Return the final run state
    let mut completed_run = {
        let orch = orchestrator.lock().unwrap();
        orch.get_run(&run.id).cloned().unwrap_or(run)
    };

    // Post-merge semantic validation: run LSP diagnostics across the workspace
    // and surface conflicts introduced by the parallel workers.
    if !completed_run.tasks.is_empty() {
        let workspace_root = state.lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
            .workspace_root
            .clone();
        completed_run.conflicts = validate_merge_semantics(&completed_run, &workspace_root);
        if !completed_run.conflicts.is_empty() {
            eprintln!(
                "[parallel] semantic merge validation found {} conflict(s) in run {}",
                completed_run.conflicts.len(),
                completed_run.id
            );
        }
    }

    completed_run
}

/// Run LSP-based semantic validation after all workers have completed.
///
/// Collects diagnostics across every file touched by the run, then filters to
/// errors/warnings that were introduced (did not exist before the run started).
/// Since we cannot snapshot the "before" state efficiently here, we report all
/// errors currently present in touched files and flag them for human review.
fn validate_merge_semantics(run: &ParallelRun, workspace_root: &std::path::Path) -> Vec<SemanticConflict> {
    // Collect every file referenced in task prompts — rough but cheap heuristic
    let touched_files: Vec<String> = run.tasks.iter()
        .flat_map(|t| extract_file_paths_from_prompt(&t.prompt))
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();

    if touched_files.is_empty() {
        return Vec::new();
    }

    let lsp = intelligence::LspManager::new(workspace_root);
    let mut conflicts = Vec::new();

    for file in &touched_files {
        let diags = lsp.get_diagnostics(file);
        for diag in diags {
            use intelligence::lsp::DiagnosticSeverity;
            let is_actionable = matches!(diag.severity, DiagnosticSeverity::Error | DiagnosticSeverity::Warning);
            if is_actionable {
                let severity_str = match diag.severity {
                    DiagnosticSeverity::Error => "error",
                    DiagnosticSeverity::Warning => "warning",
                    _ => "info",
                };
                // Find which tasks mention this file — they are the suspects
                let suspects: Vec<TaskId> = run.tasks.iter()
                    .filter(|t| t.prompt.contains(file.as_str()))
                    .map(|t| t.id.clone())
                    .collect();

                conflicts.push(SemanticConflict {
                    file: diag.file.clone(),
                    line: diag.line as u32,
                    message: diag.message.clone(),
                    severity: severity_str.to_string(),
                    suspected_tasks: suspects,
                });
            }
        }
    }

    conflicts
}

/// Extract file paths heuristically from a task prompt (workspace-relative).
fn extract_file_paths_from_prompt(prompt: &str) -> Vec<String> {
    prompt
        .split_whitespace()
        .filter(|w| {
            (w.ends_with(".rs") || w.ends_with(".ts") || w.ends_with(".py")
                || w.ends_with(".go") || w.ends_with(".js") || w.ends_with(".tsx"))
                && !w.contains("://")
        })
        .map(|w| w.trim_matches(|c: char| !c.is_alphanumeric() && c != '/' && c != '.' && c != '_' && c != '-').to_string())
        .filter(|s| !s.is_empty())
        .collect()
}

fn execute_single_task(
    task: &AgentTask,
    state: &Arc<Mutex<super::DaemonState>>,
) -> TaskResult {
    // Extract all cloneable data from state before releasing the lock so that
    // run_agent (which re-locks state for webhook firing) does not deadlock.
    let (workspace_root, file_locks, config, registry, governance, intel_cfg) = {
        let s = state.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
        let workspace_root = task.work_dir.clone().unwrap_or_else(|| s.workspace_root.clone());
        let file_locks = s.file_locks.clone();

        let template = s.config.agent_templates.iter()
            .find(|t| t.name == task.template)
            .cloned()
            .unwrap_or_else(|| {
                let mut t = platform::AgentTemplate::chat_assistant();
                t.name = task.template.clone();
                t
            });

        let mut template = template;
        if let Some(model) = &task.model {
            template.model = model.clone();
        }

        let config = platform::AgentConfig {
            template,
            session_id: format!("sess-{}", task.id),
            working_directory: workspace_root.to_string_lossy().to_string(),
            environment: std::collections::BTreeMap::new(),
        };

        (
            workspace_root,
            file_locks,
            config,
            s.registry.clone(),
            s.config.governance.clone(),
            s.config.intelligence.clone(),
        )
    }; // lock released here — safe to re-acquire inside run_agent

    // Build a fresh audit logger for this task so we don't need to clone the
    // shared one (AuditLogger holds Box<dyn AuditSink> which is not Clone).
    let task_audit = audit::AuditLogger::new();

    let result = super::AgentEngine::run_agent(
        &task.id,
        &config,
        &task.prompt,
        &registry,
        &governance,
        &task_audit,
        &intel_cfg,
        &workspace_root,
        Some(file_locks.clone()),
        Some(Arc::clone(state)),
    );

    // Release all file locks held by this agent on completion
    file_locks.release_all(&task.id);

    // Get the final audit hash from the shared state logger (it will have been
    // updated by the daemon's own sink during tool calls via the shared state).
    let audit_hash = state.lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
        .audit_logger
        .last_hash();

    TaskResult {
        success: result.success,
        summary: result.summary,
        iterations: result.iterations,
        tool_invocations: result.tool_invocations,
        audit_hash,
        tokens_in: 0,
        tokens_out: 0,
        cost_usd: 0.0,
    }
}

fn now_epoch() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

use platform;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_queue_respects_priority() {
        let mut q = TaskQueue::new();
        q.enqueue(AgentTask {
            id: "low".into(), run_id: "r1".into(), template: "chat".into(),
            prompt: "a".into(), model: None, deps: vec![], priority: 1,
            status: TaskStatus::Queued, result: None, created_at: 0,
            started_at: None, completed_at: None, work_dir: None,
        });
        q.enqueue(AgentTask {
            id: "high".into(), run_id: "r1".into(), template: "chat".into(),
            prompt: "b".into(), model: None, deps: vec![], priority: 10,
            status: TaskStatus::Queued, result: None, created_at: 0,
            started_at: None, completed_at: None, work_dir: None,
        });
        let next = q.poll(&[]).unwrap();
        assert_eq!(next.id, "high");
    }

    #[test]
    fn task_queue_respects_dependencies() {
        let mut q = TaskQueue::new();
        q.enqueue(AgentTask {
            id: "t2".into(), run_id: "r1".into(), template: "chat".into(),
            prompt: "b".into(), model: None, deps: vec!["t1".into()], priority: 5,
            status: TaskStatus::Queued, result: None, created_at: 0,
            started_at: None, completed_at: None, work_dir: None,
        });
        // t2 depends on t1, which isn't completed yet
        assert!(q.poll(&[]).is_none());
        // Now t1 is completed
        let next = q.poll(&["t1".into()]).unwrap();
        assert_eq!(next.id, "t2");
    }

    #[test]
    fn orchestrator_tracks_completion() {
        let mut orch = Orchestrator::new(4);
        let run = ParallelRun {
            id: "run-1".into(),
            tasks: vec![
                AgentTask {
                    id: "t1".into(), run_id: "run-1".into(), template: "chat".into(),
                    prompt: "a".into(), model: None, deps: vec![], priority: 5,
                    status: TaskStatus::Pending, result: None, created_at: 0,
                    started_at: None, completed_at: None, work_dir: None,
                },
            ],
            status: RunStatus::Running,
            created_at: 0,
            max_concurrency: 4,
            conflicts: vec![],
        };
        orch.submit(run);
        let task = orch.next_task().unwrap();
        assert_eq!(task.id, "t1");
        orch.complete_task("t1", TaskResult {
            success: true, summary: "done".into(), iterations: 1,
            tool_invocations: 0, audit_hash: "abc".into(),
            tokens_in: 0, tokens_out: 0, cost_usd: 0.0,
        });
        let run = orch.get_run("run-1").unwrap();
        assert_eq!(run.status, RunStatus::Completed);
    }

    // -----------------------------------------------------------------------
    // Wave 2B: RunCost aggregation
    // -----------------------------------------------------------------------

    fn task_with_cost(id: &str, run_id: &str, tokens_in: u32, tokens_out: u32, cost: f32) -> AgentTask {
        AgentTask {
            id: id.into(), run_id: run_id.into(), template: "chat".into(),
            prompt: "p".into(), model: None, deps: vec![], priority: 5,
            status: TaskStatus::Completed,
            result: Some(TaskResult {
                success: true, summary: "ok".into(), iterations: 1,
                tool_invocations: 0, audit_hash: "h".into(),
                tokens_in, tokens_out, cost_usd: cost,
            }),
            created_at: 0, started_at: None, completed_at: None, work_dir: None,
        }
    }

    #[test]
    fn run_cost_sums_tokens_correctly() {
        let run = ParallelRun {
            id: "rc-1".into(),
            tasks: vec![
                task_with_cost("t1", "rc-1", 100, 50, 0.001),
                task_with_cost("t2", "rc-1", 200, 80, 0.002),
            ],
            status: RunStatus::Completed,
            created_at: 0,
            max_concurrency: 2,
            conflicts: vec![],
        };
        let cost = RunCost::from_run(&run);
        assert_eq!(cost.total_tokens_in, 300);
        assert_eq!(cost.total_tokens_out, 130);
        assert_eq!(cost.total_tokens, 430);
        assert!((cost.estimated_cost_usd - 0.003).abs() < 1e-6);
        assert_eq!(cost.task_count, 2);
        assert_eq!(cost.tasks_with_cost, 2);
    }

    #[test]
    fn run_cost_zero_when_no_token_data() {
        let run = ParallelRun {
            id: "rc-2".into(),
            tasks: vec![
                AgentTask {
                    id: "t1".into(), run_id: "rc-2".into(), template: "chat".into(),
                    prompt: "p".into(), model: None, deps: vec![], priority: 5,
                    status: TaskStatus::Pending, result: None,
                    created_at: 0, started_at: None, completed_at: None, work_dir: None,
                },
            ],
            status: RunStatus::Running,
            created_at: 0,
            max_concurrency: 1,
            conflicts: vec![],
        };
        let cost = RunCost::from_run(&run);
        assert_eq!(cost.total_tokens, 0);
        assert_eq!(cost.estimated_cost_usd, 0.0);
        assert_eq!(cost.tasks_with_cost, 0);
    }

    #[test]
    fn task_result_serde_roundtrip_with_cost_fields() {
        let r = TaskResult {
            success: true, summary: "ok".into(), iterations: 2,
            tool_invocations: 3, audit_hash: "abc".into(),
            tokens_in: 512, tokens_out: 256, cost_usd: 0.0042,
        };
        let json = serde_json::to_string(&r).unwrap();
        let decoded: TaskResult = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.tokens_in, 512);
        assert_eq!(decoded.tokens_out, 256);
        assert!((decoded.cost_usd - 0.0042).abs() < 1e-6);
    }

    #[test]
    fn task_result_serde_defaults_when_cost_fields_absent() {
        // Older JSONL records won't have tokens_in/tokens_out/cost_usd
        let json = r#"{"success":true,"summary":"ok","iterations":1,"tool_invocations":0,"audit_hash":"h"}"#;
        let r: TaskResult = serde_json::from_str(json).unwrap();
        assert_eq!(r.tokens_in, 0);
        assert_eq!(r.tokens_out, 0);
        assert_eq!(r.cost_usd, 0.0);
    }
}
