use serde::{Deserialize, Serialize};

/// Configuration for the plan executor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanConfig {
    pub max_steps: usize,
    pub max_revisions: usize,
    pub auto_commit: bool,
    pub auto_branch: bool,
    pub auto_test: bool,
}

impl Default for PlanConfig {
    fn default() -> Self {
        Self {
            max_steps: 10,
            max_revisions: 3,
            auto_commit: true,
            auto_branch: true,
            auto_test: true,
        }
    }
}

/// A plan generated by the model before execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Plan {
    pub id: String,
    pub prompt: String,
    pub steps: Vec<PlanStep>,
    pub current_step: usize,
    pub status: PlanStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub number: usize,
    pub description: String,
    pub instruction: String,
    pub expected_files: Vec<String>,
    pub status: StepStatus,
    pub result: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PlanStatus { Created, InProgress, Completed, Failed, Revised }

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum StepStatus { Pending, Running, Completed, Failed, Skipped }

/// Result of executing a full plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanExecutionResult {
    pub plan: Plan,
    pub total_iterations: usize,
    pub total_tool_invocations: u32,
    pub revisions: usize,
    pub success: bool,
}

#[derive(Debug)]
pub enum PlanError {
    PlanGeneration(String),
    StepFailed { step: usize, reason: String },
    MaxRevisions,
    Runtime(runtime::RuntimeError),
}

impl std::fmt::Display for PlanError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::PlanGeneration(e) => write!(f, "plan generation failed: {e}"),
            Self::StepFailed { step, reason } => write!(f, "step {step} failed: {reason}"),
            Self::MaxRevisions => write!(f, "max plan revisions exceeded"),
            Self::Runtime(e) => write!(f, "runtime error: {e}"),
        }
    }
}

impl std::error::Error for PlanError {}

impl From<runtime::RuntimeError> for PlanError {
    fn from(e: runtime::RuntimeError) -> Self {
        Self::Runtime(e)
    }
}

/// The plan executor — wraps ConversationRuntime in a planning loop.
pub struct PlanExecutor;

impl PlanExecutor {
    /// Build the planning prompt for the LLM.
    pub fn build_planning_prompt(user_prompt: &str, codebase_summary: Option<&str>) -> String {
        let context = codebase_summary.unwrap_or("No codebase index available.");
        format!(
            "You are a planning agent. Given the user's task, create a numbered plan.\n\
             Return ONLY a JSON object with this structure:\n\
             {{\n  \"steps\": [\n    {{\n      \"number\": 1,\n      \"description\": \"Short description\",\n      \"instruction\": \"Detailed instruction for the agent\",\n      \"expected_files\": [\"path/to/file\"]\n    }}\n  ]\n}}\n\n\
             Rules:\n\
             - Each step should be atomic and independently verifiable\n\
             - Steps should be ordered by dependency\n\
             - Keep steps small — prefer 3-5 steps over 1 giant step\n\
             - Include file paths the step will read or modify\n\
             - The instruction should be specific enough for an AI agent to execute\n\n\
             User's task: {user_prompt}\n\n\
             Project context:\n{context}"
        )
    }

    /// Parse a plan from the LLM's JSON response.
    pub fn parse_plan(response: &str, original_prompt: &str) -> Result<Plan, PlanError> {
        // Try to find JSON in the response
        let json_start = response.find('{').ok_or_else(|| {
            PlanError::PlanGeneration("no JSON object found in response".to_string())
        })?;
        let json_end = response.rfind('}').ok_or_else(|| {
            PlanError::PlanGeneration("no closing brace found".to_string())
        })?;

        let json_str = &response[json_start..=json_end];
        let parsed: serde_json::Value = serde_json::from_str(json_str).map_err(|e| {
            PlanError::PlanGeneration(format!("invalid JSON: {e}"))
        })?;

        let steps_array = parsed
            .get("steps")
            .and_then(|v| v.as_array())
            .ok_or_else(|| PlanError::PlanGeneration("missing 'steps' array".to_string()))?;

        let steps: Vec<PlanStep> = steps_array
            .iter()
            .enumerate()
            .map(|(i, step)| PlanStep {
                number: step.get("number").and_then(|v| v.as_u64()).unwrap_or(i as u64 + 1) as usize,
                description: step.get("description").and_then(|v| v.as_str()).unwrap_or("").to_string(),
                instruction: step.get("instruction").and_then(|v| v.as_str()).unwrap_or("").to_string(),
                expected_files: step
                    .get("expected_files")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter().filter_map(|v| v.as_str().map(String::from)).collect())
                    .unwrap_or_default(),
                status: StepStatus::Pending,
                result: None,
            })
            .filter(|s| !s.instruction.is_empty())
            .collect();

        if steps.is_empty() {
            return Err(PlanError::PlanGeneration("no valid steps in plan".to_string()));
        }

        let id = format!("plan-{}", std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis());

        Ok(Plan {
            id,
            prompt: original_prompt.to_string(),
            steps,
            current_step: 0,
            status: PlanStatus::Created,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_valid_plan() {
        let json = r#"{"steps":[
            {"number":1,"description":"Read the file","instruction":"Read src/main.rs","expected_files":["src/main.rs"]},
            {"number":2,"description":"Fix the bug","instruction":"Edit src/main.rs to fix the null check","expected_files":["src/main.rs"]}
        ]}"#;

        let plan = PlanExecutor::parse_plan(json, "fix the bug").expect("should parse");
        assert_eq!(plan.steps.len(), 2);
        assert_eq!(plan.steps[0].number, 1);
        assert_eq!(plan.steps[0].status, StepStatus::Pending);
        assert_eq!(plan.status, PlanStatus::Created);
        assert!(plan.steps[0].instruction.contains("Read src/main.rs"));
    }

    #[test]
    fn parse_plan_with_surrounding_text() {
        let response = "Here's my plan:\n{\"steps\":[{\"number\":1,\"description\":\"test\",\"instruction\":\"do something\",\"expected_files\":[]}]}\nDone!";
        let plan = PlanExecutor::parse_plan(response, "test").expect("should parse");
        assert_eq!(plan.steps.len(), 1);
    }

    #[test]
    fn parse_plan_rejects_empty_steps() {
        let json = r#"{"steps":[]}"#;
        let result = PlanExecutor::parse_plan(json, "test");
        assert!(matches!(result, Err(PlanError::PlanGeneration(_))));
    }

    #[test]
    fn parse_plan_rejects_no_json() {
        let result = PlanExecutor::parse_plan("no json here", "test");
        assert!(matches!(result, Err(PlanError::PlanGeneration(_))));
    }

    #[test]
    fn planning_prompt_includes_task() {
        let prompt = PlanExecutor::build_planning_prompt("add rate limiting", Some("42 files, rust"));
        assert!(prompt.contains("add rate limiting"));
        assert!(prompt.contains("42 files"));
    }

    #[test]
    fn plan_steps_all_pending() {
        let json = r#"{"steps":[
            {"number":1,"description":"a","instruction":"do a","expected_files":[]},
            {"number":2,"description":"b","instruction":"do b","expected_files":[]}
        ]}"#;
        let plan = PlanExecutor::parse_plan(json, "test").unwrap();
        assert!(plan.steps.iter().all(|s| s.status == StepStatus::Pending));
    }

    #[test]
    fn plan_config_defaults() {
        let config = PlanConfig::default();
        assert_eq!(config.max_steps, 10);
        assert_eq!(config.max_revisions, 3);
        assert!(config.auto_commit);
        assert!(config.auto_branch);
        assert!(config.auto_test);
    }
}
