//! Multi-Agent Swarm Orchestration.
//!
//! Decomposes high-level development goals into dependency-aware Task DAGs for
//! parallel execution.  Two planning modes are supported:
//!
//! 1. **Static** — one task per file, fully parallel (fallback when LLM unavailable).
//! 2. **LLM-driven** — the goal is sent to the model with a structured-output
//!    prompt; the model produces a JSON DAG with explicit inter-task dependencies.

use serde::{Deserialize, Serialize};

// ── Public types ─────────────────────────────────────────────────────────────

/// Input for the swarm planner.
#[derive(Debug, Deserialize, Serialize)]
pub struct SwarmRefactorInput {
    pub goal: String,
    pub files: Vec<String>,
    /// Optional: prefer LLM-driven DAG planning (requires Ollama running).
    #[serde(default = "default_true")]
    pub use_llm_planner: bool,
    /// Model to use for planning (default: gemma4:26b).
    #[serde(default = "default_model")]
    pub planner_model: String,
}

fn default_true() -> bool { true }
fn default_model() -> String { "gemma4:26b".to_string() }

/// A plan generated by the swarm orchestrator.
#[derive(Debug, Serialize, Deserialize)]
pub struct SwarmPlan {
    pub tasks: Vec<SwarmTask>,
    pub planner: SwarmPlannerKind,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SwarmPlannerKind {
    Static,
    LlmDriven,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SwarmTask {
    pub id: String,
    pub template: String,
    pub prompt: String,
    /// IDs of tasks that must complete before this one starts.
    pub deps: Vec<String>,
}

// ── Planning ─────────────────────────────────────────────────────────────────

/// Decompose a goal into a DAG of agent tasks.
///
/// Tries LLM-driven planning first (if `use_llm_planner` is true and Ollama is
/// reachable), falling back to static one-task-per-file decomposition.
pub fn plan_swarm_refactor(input: &SwarmRefactorInput) -> SwarmPlan {
    if input.use_llm_planner {
        if let Some(plan) = try_llm_plan(input) {
            return plan;
        }
    }
    static_plan(input)
}

/// Static fallback: one independent task per file, fully parallel.
fn static_plan(input: &SwarmRefactorInput) -> SwarmPlan {
    // Heuristic grouping: if >10 files, create a coordinator task that depends
    // on all per-file tasks to write a summary.
    let tasks: Vec<SwarmTask> = input.files.iter().enumerate().map(|(i, file)| {
        SwarmTask {
            id: format!("file-{i}"),
            template: "refactor".to_string(),
            prompt: format!(
                "Goal: {goal}\n\nTarget file: {file}\n\n\
                 Apply the goal to this file only. \
                 Run tests after to verify correctness.",
                goal = input.goal,
                file = file,
            ),
            deps: Vec::new(),
        }
    }).collect();

    let mut all_tasks = tasks;

    // Add a coordinator step for non-trivial swarms
    if all_tasks.len() > 1 {
        let all_ids: Vec<String> = all_tasks.iter().map(|t| t.id.clone()).collect();
        all_tasks.push(SwarmTask {
            id: "coordinator".to_string(),
            template: "code-reviewer".to_string(),
            prompt: format!(
                "All per-file tasks for the following goal have completed:\n\n\
                 Goal: {goal}\n\n\
                 Files touched: {files}\n\n\
                 Review the overall result: check for consistency across files, \
                 run the full test suite, and write a summary of what changed.",
                goal = input.goal,
                files = input.files.join(", "),
            ),
            deps: all_ids,
        });
    }

    SwarmPlan { tasks: all_tasks, planner: SwarmPlannerKind::Static }
}

/// Try to generate a dependency-aware DAG using the local LLM.
///
/// Calls `ollama run <model>` with a structured JSON prompt.  If Ollama is
/// unreachable or returns unparseable output, returns `None`.
fn try_llm_plan(input: &SwarmRefactorInput) -> Option<SwarmPlan> {
    let prompt = build_planner_prompt(input);

    // Call Ollama via the CLI (no async runtime needed in intelligence crate).
    let output = std::process::Command::new("ollama")
        .args(["run", &input.planner_model, "--format", "json"])
        .arg(&prompt)
        .output()
        .ok()?;

    if !output.status.success() { return None; }

    let text = String::from_utf8_lossy(&output.stdout);
    parse_llm_plan_response(&text, input)
}

/// Build the structured prompt for LLM-driven DAG planning.
fn build_planner_prompt(input: &SwarmRefactorInput) -> String {
    let file_list = input.files.iter()
        .enumerate()
        .map(|(i, f)| format!("  file-{i}: {f}"))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"You are a software architect planning a parallel agent swarm.

Goal: {goal}

Files available (use these IDs exactly):
{file_list}

Output a JSON object with exactly this schema:
{{
  "tasks": [
    {{
      "id": "unique-id",
      "template": "refactor|code-reviewer|test-runner|doc-generator",
      "prompt": "Detailed instruction for the agent",
      "deps": ["id-of-dependency", ...]
    }}
  ]
}}

Rules:
- Every file should appear in at least one task's prompt.
- Use deps to encode real ordering constraints (e.g. a review after an edit).
- Prefer parallelism: only add deps when strictly necessary.
- A final "coordinator" task may depend on all others to write a summary.
- Output ONLY valid JSON, no markdown, no explanation."#,
        goal = input.goal,
        file_list = file_list,
    )
}

/// Parse the LLM response and patch in missing fields.
fn parse_llm_plan_response(text: &str, input: &SwarmRefactorInput) -> Option<SwarmPlan> {
    // Strip markdown fences if the model ignored the no-markdown rule
    let clean = strip_markdown_fences(text.trim());

    let parsed: serde_json::Value = serde_json::from_str(clean).ok()?;
    let tasks_json = parsed.get("tasks")?.as_array()?;

    let tasks: Vec<SwarmTask> = tasks_json.iter().filter_map(|t| {
        let id       = t["id"].as_str()?.to_string();
        let template = t["template"].as_str().unwrap_or("refactor").to_string();
        let prompt   = t["prompt"].as_str().unwrap_or("").to_string();
        let deps     = t["deps"].as_array()
            .map(|arr| arr.iter().filter_map(|v| v.as_str().map(str::to_string)).collect())
            .unwrap_or_default();
        if prompt.is_empty() { return None; }
        Some(SwarmTask { id, template, prompt, deps })
    }).collect();

    if tasks.is_empty() { return None; }

    // Validate: every dep ID must refer to an existing task
    let ids: std::collections::HashSet<&str> = tasks.iter().map(|t| t.id.as_str()).collect();
    for task in &tasks {
        for dep in &task.deps {
            if !ids.contains(dep.as_str()) {
                eprintln!("[swarm] LLM plan has dangling dep '{dep}' in task '{}' — falling back to static", task.id);
                return None;
            }
        }
    }

    // Sanity-check: all input files appear somewhere
    let plan_text = serde_json::to_string(&tasks).unwrap_or_default();
    let missing: Vec<&str> = input.files.iter()
        .filter(|f| !plan_text.contains(f.as_str()))
        .map(String::as_str)
        .collect();
    if !missing.is_empty() {
        eprintln!("[swarm] LLM plan omits files {missing:?} — falling back to static");
        return None;
    }

    Some(SwarmPlan { tasks, planner: SwarmPlannerKind::LlmDriven })
}

fn strip_markdown_fences(s: &str) -> &str {
    let s = if s.starts_with("```") {
        s.find('\n').map(|i| &s[i + 1..]).unwrap_or(s)
    } else { s };
    if s.ends_with("```") { &s[..s.len() - 3] } else { s }
}

// ── Entry point ──────────────────────────────────────────────────────────────

/// Execute planning and return the DAG as pretty-printed JSON.
pub fn execute_swarm_refactor(input: &SwarmRefactorInput) -> Result<String, String> {
    let plan = plan_swarm_refactor(input);
    serde_json::to_string_pretty(&plan).map_err(|e| e.to_string())
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn input(files: &[&str]) -> SwarmRefactorInput {
        SwarmRefactorInput {
            goal: "Rename `foo` to `bar` everywhere".to_string(),
            files: files.iter().map(|s| s.to_string()).collect(),
            use_llm_planner: false,
            planner_model: "gemma4:26b".to_string(),
        }
    }

    #[test]
    fn static_plan_single_file_no_coordinator() {
        let plan = plan_swarm_refactor(&input(&["src/lib.rs"]));
        assert_eq!(plan.tasks.len(), 1);
        assert_eq!(plan.planner, SwarmPlannerKind::Static);
        assert!(plan.tasks[0].deps.is_empty());
    }

    #[test]
    fn static_plan_multi_file_adds_coordinator() {
        let plan = plan_swarm_refactor(&input(&["a.rs", "b.rs", "c.rs"]));
        // 3 file tasks + 1 coordinator
        assert_eq!(plan.tasks.len(), 4);
        let coord = plan.tasks.iter().find(|t| t.id == "coordinator").expect("coordinator missing");
        assert_eq!(coord.deps.len(), 3);
        assert!(coord.deps.contains(&"file-0".to_string()));
    }

    #[test]
    fn static_plan_prompts_include_goal_and_file() {
        let plan = plan_swarm_refactor(&input(&["src/main.rs"]));
        let task = &plan.tasks[0];
        assert!(task.prompt.contains("Rename `foo` to `bar`"));
        assert!(task.prompt.contains("src/main.rs"));
    }

    #[test]
    fn execute_returns_valid_json() {
        let inp = input(&["x.rs"]);
        let json = execute_swarm_refactor(&inp).expect("should succeed");
        let v: serde_json::Value = serde_json::from_str(&json).expect("valid json");
        assert!(v["tasks"].is_array());
        assert_eq!(v["planner"], "static");
    }

    #[test]
    fn strip_fences_works() {
        assert_eq!(strip_markdown_fences("```json\n{}\n```"), "{}\n");
        assert_eq!(strip_markdown_fences("{}"), "{}");
    }
}
